from gettext import gettext as _

NEW_USER_START_MESSAGE = _("NEW_USER_START_MESSAGE")

START_MESSAGE = _("START_MESSAGE")

SELECT_NEW_LANGUAGE = _("SELECT_NEW_LANGUAGE")

LANGUAGE_SELECTED = _("LANGUAGE_SELECTED")

ALLOW_NOTIFICATIONS = _("ALLOW_NOTIFICATIONS")

NOTIFICATIONS_ARE_ON = _("NOTIFICATIONS_ARE_ON")

NOTIFICATIONS_ARE_OFF = _("NOTIFICATIONS_ARE_OFF")

SELECT_BUTTONS = _("SELECT_BUTTONS")

EXAM = _("EXAM")

ALL_TICKETS = _("ALL_TICKETS")

YES = _("YES")

NO = _("NO")

SELECT_CATEGORY = _("SELECT_CATEGORY")

DECLINE = _("DECLINE")

UNKNOWN_ACTION = _("UNKNOWN_ACTION")

EXAM_STARTED = _("EXAM_STARTED")

EXAM_FINISHED = _("EXAM_FINISHED")

WHICH_ANSWER_CHOSEN = _("WHICH_ANSWER_CHOSEN")

DROP_PASSED_TICKETS_HISTORY = _("DROP_PASSED_TICKETS_HISTORY")

CONFIRM_CLEAR_HISTORY = _("CONFIRM_CLEAR_HISTORY")

HISTORY_IS_CLEAR = _("HISTORY_IS_CLEAR")

HISTORY_IS_NOT_CLEAR = _("HISTORY_IS_NOT_CLEAR")

ACTION_DECLINED = _("ACTION_DECLINED")

SESSION_IS_OVER = _("SESSION_IS_OVER")

ABOUT_MESSAGE = _("ABOUT_MESSAGE")

REPLY_BOT_MESSAGE = _("REPLY_BOT_MESSAGE")

DESCRIBE_YOUR_PROBLEM = _("DESCRIBE_YOUR_PROBLEM")

EXPLAIN_TRANSLATION_ERROR = _("EXPLAIN_TRANSLATION_ERROR")

CONTINUE_EXAM = _("CONTINUE_EXAM")

EXAM_PASSED = _("EXAM_PASSED")

EXAM_FAILED = _("EXAM_FAILED")

API_COMMAND_RESPONSE = _("API_COMMAND_RESPONSE")

HTTP_REST_INFO = _("HTTP_REST_INFO")

GRPC_INFO = _("GRPC_INFO")

NEW_API_TOKEN = _("NEW_API_TOKEN")

EXISTING_API_TOKEN = _("EXISTING_API_TOKEN")

GENERATE_NEW_TOKEN = _("GENERATE_NEW_TOKEN")

REISSUED_TOKEN = _("REISSUED_TOKEN")

MESSAGE_TOO_LONG = _("MESSAGE_TOO_LONG")

PROBLEM_IN_PROGRESS = _("PROBLEM_IN_PROGRESS")

WRITE_ME_BUTTON = _("WRITE_ME_BUTTON")

WRITE_ME_BUTTON_RESPONSE = _("WRITE_ME_BUTTON_RESPONSE")

PROBLEM_RESOLVED_MESSAGE = _("PROBLEM_RESOLVED_MESSAGE")

TRANSLATION_PROBLEM_IN_PROGRESS = _("TRANSLATION_PROBLEM_IN_PROGRESS")

DONATE_MESSAGE = _("DONATE_MESSAGE")
